#IMAGE PROCESSING
#HOW DO COMPUTERS HANDLE IMAGES
#FEW KEYPOINTS
#COMPUTERS STORE IMAGES AS TINY SQUARE
#EACH SQUARE IS CALLED A PIXEL. 
#A SIMPLE WAY OF DESCRIBING 1 PIXEL ES THROUGH A COMBINATION OF THREE COLOURS
#THREE 8-BIT NUMBERS. RGB IMAGES, COMBINATION OF THESE THREE WILL PRODUCE A DIFFERENT COLOUR
#8BITS --- 0/255


#IMPORTING AN RGB IMAGE INTO PYTHON 
from skimage import data
photo_data=